CLASS zbp_i_bookingsuppl_5364 DEFINITION PUBLIC ABSTRACT FINAL FOR BEHAVIOR OF z_i_travel_5364.
protected section.
private section.
ENDCLASS.



CLASS ZBP_I_BOOKINGSUPPL_5364 IMPLEMENTATION.
ENDCLASS.
